### PR TITLE
Add `onBeforeExit`

### PR DESCRIPTION
**Pull request by Vivalldi**
Hey @HiDeoo!
Hope all is going well. Just added this new feature. Would love to see this added

Cheers,
Vivalldi

### CODE REVIEW

**Comment by HiDeoo** [comment]
Hi, thanks for your PR :)

Indeed, that seems like a pretty nice addition. I haven't look at the code / tests yet but if you manage to fix them I'll review everything at once and merge the PR.

If you need help regarding the tests, let me know and I'll take a look tomorrow.

PS: The new callback would also need to be documented in the `README` like the other ones.

**Comment by Vivalldi** [comment]
Yeah I had realized that there we're checks. I'll be running through those shortly. Do you have a config file for `prettier`?

**Comment by HiDeoo** [comment]
No problem, and yes, the project was created a little bit before Prettier added support for `.prettierrc` and others config files and I never updated it with a proper config.

I'll make sure to add one before the next release, good call. In the meantime, you can find the options I used [in the `lint-staged` configuration](https://github.com/HiDeoo/intro.js-react/blob/master/package.json#L68):

`prettier --single-quote --trailing-comma es5 --print-width 120 --write`

**Comment by Vivalldi** [comment]
Having some issues mocking the onBeforeExit function...

**Pull request closed without merging**
