### PR TITLE
Add `onBeforeExit` callback

### PR DESCRIPTION
**Pull request by Vivalldi**
#11 Cleaned-up

### CODE REVIEW

**Comment by HiDeoo** [comment]
Thanks for the PR, I just merged this into master!

I took the liberty to modify some comments and also change the mock you added, I think it was invoked even when not necessary, but besides that, everything was neat 👍 

This will be published in the next `intro.js-react v0.2.0` release which will be released when `intro.js v2.8.0` is out of alpha (altho, if you really need the feature right now, you can still use the master branch in your `package.json` until then).

I also took your suggestion of [adding a proper Prettier configuration](https://github.com/HiDeoo/intro.js-react/commit/a475b7968067e5c5778e431d6448ef46aa576761) as it's now supported.🎉 .

**Comment by Vivalldi** [comment]
Would you be able to tag the commit with the prerelease? Yarn is not picking it up as of right now

**Comment by HiDeoo** [comment]
Strange, what did you try?

I just tried (I removed the package before each try to be sure):

`yarn add https://github.com/HiDeoo/intro.js-react`
`yarn add https://github.com/HiDeoo/intro.js-react#master`
`yarn add https://github.com/HiDeoo/intro.js-react#a475b79`

and the 3 commands work and pickup the code with the latest changes from `master` so if even specifying a specific commit number don't work, I don't think a tag would. Maybe it's an issue in Yarn or a specific version of Yarn (for info I use `v1.3.2`)?

**Comment by Vivalldi** [comment]
Ah okay. I was trying to use an alpha release tag even though you haven't done an alpha release tag. I'll just that. Thanks.

**Pull request merged**
