### PR TITLE
Remove required from element

### PR DESCRIPTION
**Pull request by lstaniszewski**
Hi!

First great job with this project.

I'm using this in my project and I found out that it is possible to set step to be floating and all you need to do is not pass element prop, sadly you set element to required and I think it may be worth changing this.

### CODE REVIEW

**Comment by lstaniszewski** [comment]
Thanks @HiDeoo ! 
Can you also update this on npm?

**Comment by HiDeoo** [comment]
@lstaniszewski I'm on it, upgrading documentation to reflect your change 👍

**Comment by lstaniszewski** [comment]
Nice! Thanks. I will let myself do another PR if I find anything else to be more strict with intro.js.
But next time I will try to update readme/tests if needed

**Comment by HiDeoo** [comment]
No problem, thanks for your contribution.

Version `0.1.4` is now available on npmjs with your change 🎉

**Pull request merged**
